stages:
- name: Publish chart
  steps:
  - publishCatalogConfig:
      path: Chart/
      catalogTemplate: OL-Chart
      version: ${CICD_GIT_COMMIT}
      gitUrl: https://harbor.ornell.io/ol/library
      gitBranch: master
      gitAuthor: ornell
      gitEmail: thomas@ornell.no
    envFrom:
    - sourceName: deploykey
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: deploykey
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
