apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: {{ .Release.Name }}
    uid: c804bce0-c476-4d25-b2b5-8fab72f5c9123
spec:
  ports:
  - name: api
    port: {{ .Values.port }}
    protocol: TCP
    targetPort: {{ .Values.port }}
  selector:
    workload.user.cattle.io/workloadselector: {{ .Release.Name }}
  sessionAffinity: None
  type: ClusterIP
